### ISSUE TITLE
wrong number of arguments (1 for 2)

### ISSUE THREAD

**Issue by zedtux** [alexspeller/emblem-rails#38]
I have a brand now Rails application with ember. I have the following error:

``` bash
ActionView::Template::Error (wrong number of arguments (1 for 2)):
     5:     meta charset="UTF-8"
     6:     meta name="viewport" content="width=device-width, initial-scale=1.0"
     7:     == stylesheet_link_tag    'application', media: 'all'
     8:     == javascript_include_tag 'application'
     9:     == csrf_meta_tags
    10: 
    11:   body
  app/views/layouts/application.html.slim:8:in `_app_views_layouts_application_html_slim__2376024801504411528_69818151276080'
```

with the following backtrace:

```
ember-handlebars-template (0.2.2) lib/ember/handlebars/helper.rb:32:in `global_template_target'
emblem-rails (0.2.2) lib/emblem/rails/template.rb:11:in `evaluate'
tilt (1.4.1) lib/tilt/template.rb:103:in `render'
...
```

So `emblem-rails` [is calling the `global_template_target` method with only one parameter](https://github.com/alexspeller/emblem-rails/blob/master/lib/emblem/rails/template.rb#L11) while [`ember-handlebars-template` expect 2 parameters](https://github.com/tricknotes/ember-handlebars-template/blob/master/lib/ember/handlebars/helper.rb#L32)

**Comment by fr33z3** [comment]
Have the same problem.

**Comment by Eric-Guo** [comment]
@fr33z3 @zedtux See Issue #36

**Comment by zedtux** [comment]
Thank you @Eric-Guo for the info :)
